import { CircuitComponent, Wire } from "../types";

export const generateArduinoCode = (
  components: CircuitComponent[],
  wires: Wire[],
): string => {
  const led = components.find((component) => component.type === "led");
  const button = components.find((component) => component.type === "button");
  const ldr = components.find((component) => component.type === "ldr");

  const lines: string[] = [];
  lines.push("// Auto-generated by CircuitLab Studio");
  lines.push("#include <Arduino.h>");
  lines.push("");
  lines.push("const int LED_PIN = 3;");
  lines.push("const int BUTTON_PIN = 4;");
  lines.push("const int LDR_PIN = A0;");
  lines.push("");
  lines.push("void setup() {");
  lines.push("  Serial.begin(9600);");
  lines.push("  pinMode(LED_PIN, OUTPUT);");
  lines.push("  pinMode(BUTTON_PIN, INPUT_PULLUP);");
  lines.push("}");
  lines.push("");
  lines.push("void loop() {");
  lines.push("  int buttonState = digitalRead(BUTTON_PIN);");
  lines.push("  int ldrValue = analogRead(LDR_PIN);");
  lines.push("  Serial.print(\"Button: \");");
  lines.push("  Serial.print(buttonState);");
  lines.push("  Serial.print(\" | LDR: \");");
  lines.push("  Serial.println(ldrValue);");
  lines.push("  if (buttonState == LOW) {");
  lines.push("    digitalWrite(LED_PIN, HIGH);");
  lines.push("  } else {");
  lines.push("    digitalWrite(LED_PIN, LOW);");
  lines.push("  }");
  lines.push("  delay(100);");
  lines.push("}");
  lines.push("");
  lines.push("// Components in circuit:");
  components.forEach((component) => {
    lines.push(
      `// - ${component.label}${component.value ? ` (${component.value})` : ""}`,
    );
  });
  lines.push(`// Wires: ${wires.length}`);
  lines.push(`// LED present: ${Boolean(led)}`);
  lines.push(`// Button present: ${Boolean(button)}`);
  lines.push(`// LDR present: ${Boolean(ldr)}`);

  return lines.join("\n");
};
